#pragma once

// Keyboard Settings
#define FORCE_NKRO
#define DEBOUNCE 5

// Tap-hold
#define TAPPING_TERM 240
#define RETRO_TAPPING

// One-shot modifiers
#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_TIMEOUT 5000

// Auto-shift
#define AUTO_SHIFT_TIMEOUT 180
#define RETRO_SHIFT 500

// Combos
#define COMBO_TERM 40

// Mouse keys
#define MOUSEKEY_DELAY 5
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 1
#define MOUSEKEY_INITIAL_SPEED 1
#define MOUSEKEY_DECELERATED_SPEED 12
#define MOUSEKEY_MAX_SPEED 22
#define MOUSEKEY_WHEEL_INTERVAL 83
#define MOUSEKEY_WHEEL_INTERVAL 83
#define MOUSEKEY_WHEEL_MAX_SPEED 3
