#pragma once

// Keyboard Settings
#define FORCE_NKRO
#define DEBOUNCE 15

// Tri-layers
#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3

// Tap-hold
#define TAPPING_TOGGLE 2
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_TERM 200
#define TAP_CODE_DELAY 45

// Combos
#define COMBO_TERM 20

// Mouse acceleration
#define MOUSEKEY_INERTIAL
#define MOUSEKEY_MAX_SPEED 24
#define MOUSEKEY_DELAY 50
#define MOUSEKEY_FRICTION 48
#define MOUSEKEY_TIME_TO_MAX 64
#define MOUSEKEY_WHEEL_INTERVAL 200
#define MOUSEKEY_WHEEL_MAX_SPEED 1
