#pragma once

#define FORCE_NKRO

#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3
#define TAPPING_TERM 175
#define TAP_CODE_DELAY 25
#define COMBO_TERM 40
